version: '2'
services:
    bugzilla:
      image: uneet/bugzilla
      restart: on-failure
      ports:
        - 80:80
      environment:
            SES_SMTP_USERNAME: ${SES_SMTP_USERNAME}
            SES_SMTP_PASSWORD: ${SES_SMTP_PASSWORD}
            SES_VERIFIED_SENDER: ${SES_VERIFIED_SENDER}
            MYSQL_HOST: ${MYSQL_HOST}
            MYSQL_PORT: ${MYSQL_PORT}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      logging:
            driver: awslogs
            options:
              awslogs-region: ap-southeast-1
              awslogs-group: bugzilla

    meteor:
      image: ulexus/meteor
      ports:
       - "8080:80"
      environment:
       - BUNDLE_URL=https://unee-t-media.s3-accelerate.amazonaws.com/2017-08-31/unee-t-fe.tar.gz
       - ROOT_URL=http://app.unee-t.com
       - BUGZILLA_URL=http://bugzilla/
       - BUGZILLA_ADMIN_KEY=I6zRu7bPak687rcIBCkNbFKblfRXPn2X3xgEFz99
       - MONGO_URL=mongodb://mongo:27017/mydatabase
      logging:
            driver: awslogs
            options:
              awslogs-region: ap-southeast-1
              awslogs-group: meteor
      links:
          - "mongo"
          - "bugzilla"

    mongo:
      image: mongo
      volumes:
        - '/data/db:/data/db'
      ports:
      - "27017:27017"
      logging:
              driver: awslogs
              options:
                awslogs-region: ap-southeast-1
                awslogs-group: mongo

