version: '2'
services:
    bugzilla:
      image: registry.gitlab.com/unee-t/bugzilla:master
      restart: on-failure
      ports:
        - 8081:80
      environment:
            SES_SMTP_USERNAME: ${SES_SMTP_USERNAME}
            SES_SMTP_PASSWORD: ${SES_SMTP_PASSWORD}
            SES_VERIFIED_SENDER: ${SES_VERIFIED_SENDER}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      depends_on:
        - db
      volumes:
            - ./custom:/opt/bugzilla/template/en/custom
            - ./skin:/opt/bugzilla/skins/contrib/skin
      networks:
        - network

    db:
      image: mariadb
      ports:
        - 3306:3306
      environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      volumes:
            - ./mariadb:/var/lib/mysql
            - ./sql:/docker-entrypoint-initdb.d
      networks:
            - network

    adminer:
     image: adminer
     ports:
        - 8082:8080
     depends_on:
        - db
     networks:
        - network

networks:
    network:
        driver: bridge
