version: '3'
services:
    bugzilla:
      build: .
      environment:
          SES_SMTP_USERNAME: ${SES_SMTP_USERNAME}
          SES_SMTP_PASSWORD: ${SES_SMTP_PASSWORD}
          SES_VERIFIED_SENDER: ${SES_VERIFIED_SENDER}
      restart: on-failure
      ports:
        - 8081:80
      depends_on:
        - db
      volumes:
            - ./custom:/opt/bugzilla/template/en/custom
            - ./skin:/opt/bugzilla/skins/contrib/skin
      networks:
        - network

    db:
      image: mysql:5.6
      ports:
        - 3306:3306
      environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      volumes:
            - ./mysql:/var/lib/mysql
      networks:
            - network
      healthcheck:
           test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
           timeout: 20s
           retries: 10

    adminer:
     image: adminer
     ports:
        - 8080:8080
     depends_on:
        - db
     networks:
        - network

networks:
    network:
        driver: bridge
